---
sudo: required
dist: bionic
language: python
install:
  - pip install tox-travis
  - sudo snap refresh
  - sudo snap install --classic snapcraft
env:
 - ENV=bashate
 - ENV=inspect
script:
 - tox -e $ENV
