name: octavia-diskimage-retrofit
version: git
summary: tool for retrofitting cloud images for use as Octavia Amphora image.
description: |
  tool for retrofitting cloud images for use as Octavia Amphora image.
confinement: strict
base: core18
grade: devel
environment:
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
  LIBGUESTFS_PATH: $SNAP/lib/guestfs
apps:
  virt-dib:
    command: bin/virt-dib
parts:
  octavia:
    after: [diskimage-builder]
    plugin: dump
    source: https://opendev.org/openstack/octavia.git
    source-type: git
    source-branch: master
    organize:
      elements/*: lib/python3.6/site-packages/diskimage_builder/elements/
  diskimage-builder:
    plugin: python
    source: https://opendev.org/openstack/diskimage-builder.git
    source-type: git
    source-branch: master
  qemu:
    source: https://git.launchpad.net/ubuntu/+source/qemu
    source-type: git
    source-branch: ubuntu/bionic-security
    plugin: autotools
    override-build: |
      dpkg-source --before-build .
      snapcraftctl build
    configflags:
      - --extra-cflags=-g -O2 -fdebug-prefix-map=/home/ubuntu/qemu-2.11+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DCONFIG_QEMU_DATAPATH='"/snap/$SNAPCRAFT_PROJECT_NAME/current/share/qemu:/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/seabios:/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/ipxe/qemu"' -DVENDOR_UBUNTU
      - --extra-ldflags=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed
      - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
      - --libdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/x86_64-linux-gnu
      - --libexecdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/qemu
      - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
      - --disable-blobs
      - --disable-strip
      - --interp-prefix=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/etc/qemu-binfmt/%M
      - --disable-user
      - --enable-system
      - --enable-linux-user
      - --enable-modules
      - --enable-linux-aio
      - --audio-drv-list=pa,alsa,oss
      - --enable-attr
      - --enable-bluez
      - --enable-brlapi
      - --enable-virtfs
      - --enable-cap-ng
      - --enable-curl
      - --enable-fdt
      - --enable-gnutls
      - --disable-gtk
      - --disable-vte
      - --enable-libiscsi
      - --enable-curses
      - --enable-smartcard
      - --enable-rbd
      - --enable-rdma
      - --enable-vnc-sasl
      - --enable-seccomp
      - --enable-spice
      - --enable-libusb
      - --enable-usb-redir
      - --enable-xen
      - --enable-xfsctl
      - --enable-vnc
      - --enable-vnc-jpeg
      - --enable-vnc-png
      - --enable-kvm
      - --enable-vhost-net
    build-packages:
      - libaio-dev
      - acpica-tools
      - libasound2-dev
      - libattr1-dev
      - libcap-dev
      - libcap-ng-dev
      - libiscsi-dev
      - libnuma-dev
      - librados-dev
      - librbd-dev
      - libpixman-1-dev
      - libspice-server-dev
      - libspice-protocol-dev
      - libusb-1.0-0-dev
      - libusbredirparser-dev
      - zlib1g-dev
      - uuid-dev
      - device-tree-compiler
      - texinfo
      - libpulse-dev 
      - libbluetooth-dev
      - libbrlapi-dev 
      - libcurl4-gnutls-dev 
      - libfdt-dev 
      - gnutls-dev 
      - libcacard-dev 
      - librdmacm-dev 
      - libibverbs-dev 
      - libsasl2-dev 
      - libsdl1.2-dev 
      - libseccomp-dev
      - xfslibs-dev
      - libjpeg-dev
      - libcapstone-dev
    stage-packages:
      - seabios
      - ipxe-qemu
      - libxml2
      - libyajl2
      - libnuma1
      - libaio1
      - libiscsi7
      - libcurl3-gnutls
      - librbd1
      - librados2
      - libcairo2
      - libgdk-pixbuf2.0-0
      - libpixman-1-0
      - libgtk2.0-0
      - libspice-server1
      - libusb-1.0-0
      - libusbredirparser1
      - libxen-dev
      - libx11-6
      - libcapstone3
  libguestfs:
    after: [qemu]
    source: https://git.launchpad.net/ubuntu/+source/libguestfs
    source-type: git
    source-branch: ubuntu/bionic
    plugin: autotools
    build-environment:
      - QEMU: /snap/$SNAPCRAFT_PROJECT_NAME/current/bin/qemu-system-x86_64
    override-build: |
      dpkg-source --before-build .
      patch -p1 < ../../../project/patch/patch-ocaml-lgnu.patch
      patch -p1 < ../../../project/patch/patch-ocaml-examples-gnulib.patch
      mkdir -p /snap/$SNAPCRAFT_PROJECT_NAME
      ln -sf $SNAPCRAFT_STAGE /snap/$SNAPCRAFT_PROJECT_NAME/current
      snapcraftctl build
      rm -f /snap/$SNAPCRAFT_PROJECT_NAME/current
      rmdir /snap/$SNAPCRAFT_PROJECT_NAME
    override-prime: |
      mkdir lib/guestfs
      env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin libguestfs-make-fixed-appliance $SNAPCRAFT_PRIME/lib/guestfs
      snapcraftctl prime
    configflags:
      - --disable-silent-rules
      - --disable-gnulib-tests
      - --with-readline
      - --disable-haskell
      - --with-java=/usr/lib/jvm/java-8-openjdk-amd64
      - --disable-perl
      - --disable-php
      - --disable-appliance
      - --disable-daemon
    stage-packages:
      - libfuse2
      - libasn1-8-heimdal
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libroken18-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libwind0-heimdal
      - libicu60
      - libldap-2.4-2
      - libmagic1
      - libnghttp2-14
      - libnuma1
      - libpsl5
      - librtmp1
      - libruby2.5
      - libsasl2-2
      - libvirt0
      - libavahi-client3
      - libconfig9
      - libcurl3-gnutls
      - libxml2 
      - libyajl2
      - uuid-runtime
    build-packages:
      - libguestfs-tools
      - adwaita-icon-theme
      - attr
      - augeas-lenses
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - bison
      - ca-certificates-java
      - crda
      - db-util
      - db5.3-util
      - dconf-gsettings-backend
      - dconf-service
      - dctrl-tools
      - debhelper
      - devscripts
      - dh-autoreconf
      - dh-lua
      - dh-ocaml
      - dh-php
      - dh-python
      - dh-strip-nondeterminism
      - erlang-base
      - erlang-dev
      - exfat-utils
      - extlinux
      - flex
      - fontconfig
      - fontconfig-config
      - fonts-dejavu-core
      - gem2deb
      - gem2deb-test-runner
      - genisoimage
      - gettext
      - gfs2-utils
      - gir1.2-atk-1.0
      - gir1.2-freedesktop
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-gtk-2.0
      - gir1.2-gtk-3.0
      - gir1.2-harfbuzz-0.0
      - gir1.2-pango-1.0
      - gjs
      - glib-networking
      - glib-networking-common
      - glib-networking-services
      - gobject-introspection
      - golang-1.10-go
      - golang-1.10-src
      - golang-go
      - golang-src
      - gperf
      - gsettings-desktop-schemas
      - gtk-update-icon-cache
      - hfsplus
      - hicolor-icon-theme
      - humanity-icon-theme
      - icoutils
      - icu-devtools
      - intel-microcode
      - intltool-debian
      - iputils-arping
      - ipxe-qemu
      - ipxe-qemu-256k-compat-efi-roms
      - iucode-tool
      - iw
      - java-common
      - jfsutils
      - ldmtool
      - libacl1-dev
      - libafflib0v5
      - libaio1
      - libarchive-zip-perl
      - libasound2
      - libasound2-data
      - libasyncns0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatk1.0-data
      - libatk1.0-dev
      - libatspi2.0-0
      - libattr1-dev
      - libaugeas-dev
      - libaugeas0
      - libavahi-client3
      - libavahi-common-data
      - libavahi-common3
      - libbfio1
      - libbison-dev
      - libbluetooth3
      - libbrlapi0.6
      - libcaca0
      - libcacard0
      - libcairo-gobject2
      - libcairo-script-interpreter2
      - libcairo2
      - libcairo2-dev
      - libcamlp4-ocaml-dev
      - libcamomile-ocaml-data
      - libcamomile-ocaml-dev
      - libcap-dev
      - libcolord2
      - libconfig-dev
      - libconfig9
      - libcroco3
      - libcups2
      - libdate-manip-perl
      - libdatrie1
      - libdconf1
      - libdevel-symdump-perl
      - libdrm-amdgpu1
      - libdrm-intel1
      - libdrm-nouveau2
      - libdrm-radeon1
      - libencode-locale-perl
      - libepoxy0
      - libewf2
      - libexpat1-dev
      - libexporter-tiny-perl
      - libfdt1
      - libffi-dev
      - libfile-find-rule-perl
      - libfile-homedir-perl
      - libfile-listing-perl
      - libfile-stripnondeterminism-perl
      - libfile-which-perl
      - libfileutils-ocaml-dev
      - libfindlib-ocaml
      - libflac8
      - libfontconfig1
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfuse-dev
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libgdk-pixbuf2.0-dev
      - libgettext-ocaml
      - libgettext-ocaml-dev
      - libgif7
      - libgirepository1.0-dev
      - libgjs0g
      - libgl1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglapi-mesa
      - libglib2.0-bin
      - libglib2.0-dev
      - libglib2.0-dev-bin
      - libglvnd0
      - libglx-mesa0
      - libglx0
      - libgmp-dev
      - libgmpxx4ldbl
      - libgraphite2-3
      - libgraphite2-dev
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgtk-3-common
      - libgtk2.0-0
      - libgtk2.0-common
      - libgtk2.0-dev
      - libharfbuzz-dev
      - libharfbuzz-gobject0
      - libharfbuzz-icu0
      - libharfbuzz0b
      - libhfsp0
      - libhivex-dev
      - libhivex0
      - libhtml-parser-perl
      - libhtml-tagset-perl
      - libhtml-tree-perl
      - libhttp-cookies-perl
      - libhttp-date-perl
      - libhttp-message-perl
      - libhttp-negotiate-perl
      - libibverbs1
      - libice-dev
      - libice6
      - libicu-dev
      - libicu-le-hb-dev
      - libicu-le-hb0
      - libiculx60
      - libintl-perl
      - libio-html-perl
      - libio-socket-ssl-perl
      - libiscsi7
      - libjbig0
      - libjpeg-turbo8
      - libjpeg8
      - libjs-jquery
      - libjson-glib-1.0-0
      - libjson-glib-1.0-common
      - liblcms2-2
      - libldm-1.0-0
      - liblist-moreutils-perl
      - libllvm7
      - liblua5.1-0
      - liblua5.1-0-dev
      - liblua5.2-0
      - liblua5.2-dev
      - liblua5.3-0
      - liblua5.3-dev
      - libluasandbox-bin
      - libluasandbox-dev
      - libluasandbox0
      - liblwp-mediatypes-perl
      - liblwp-protocol-https-perl
      - liblzma-dev
      - libmagic-dev
      - libmodule-build-perl
      - libmozjs-52-0
      - libncurses5-dev
      - libncursesw5-dev
      - libnet-http-perl
      - libnet-ssleay-perl
      - libnetpbm10
      - libnl-3-200
      - libnl-genl-3-200
      - libnl-route-3-200
      - libnspr4
      - libnss3
      - libnumber-compare-perl
      - libogg0
      - libopus0
      - liborc-0.4-0
      - libosp5
      - libpango-1.0-0
      - libpango1.0-dev
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpangoxft-1.0-0
      - libpciaccess0
      - libpcre-ocaml
      - libpcre-ocaml-dev
      - libpcre16-3
      - libpcre3-dev
      - libpcre32-3
      - libpcrecpp0v5
      - libpcsclite1
      - libpixman-1-0
      - libpixman-1-dev
      - libpng-dev
      - libpod-coverage-perl
      - libproxy1v5
      - libpthread-stubs0-dev
      - libpulse0
      - libpython-all-dev
      - libpython-dev
      - libpython-stdlib
      - libpython2.7
      - libpython2.7-dev
      - libpython2.7-minimal
      - libpython2.7-stdlib
      - libpython3-all-dev
      - libpython3-dev
      - libpython3.6-dev
      - librados2
      - librbd1
      - librdmacm1
      - libreadline-dev
      - librest-0.7-0
      - librsvg2-2
      - librsvg2-common
      - libruby2.5
      - libsdl1.2debian
      - libselinux1-dev
      - libsensors4
      - libsepol1-dev
      - libsgmls-perl
      - libsm-dev
      - libsm6
      - libsndfile1
      - libsodium23
      - libsoup-gnome2.4-1
      - libsoup2.4-1
      - libspice-server1
      - libssl-dev
      - libstring-shellquote-perl
      - libsys-virt-perl
      - libsystemd-dev
      - libtest-pod-coverage-perl
      - libtest-pod-perl
      - libtext-glob-perl
      - libthai-data
      - libthai0
      - libtiff5
      - libtimedate-perl
      - libtinfo-dev
      - libtool
      - libtool-bin
      - libtry-tiny-perl
      - libtsk-dev
      - libtsk13
      - liburi-perl
      - libusbredirparser1
      - libvirt-dev
      - libvirt0
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwin-hivex-perl
      - libwww-perl
      - libwww-robotrules-perl
      - libx11-dev
      - libx11-xcb1
      - libxau-dev
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxcb-render0
      - libxcb-render0-dev
      - libxcb-shm0
      - libxcb-shm0-dev
      - libxcb-sync1
      - libxcb1-dev
      - libxcomposite-dev
      - libxcomposite1
      - libxcursor-dev
      - libxcursor1
      - libxdamage-dev
      - libxdamage1
      - libxdmcp-dev
      - libxen-4.9
      - libxen-dev
      - libxenstore3.0
      - libxext-dev
      - libxfixes-dev
      - libxfixes3
      - libxft-dev
      - libxft2
      - libxi-dev
      - libxi6
      - libxinerama-dev
      - libxinerama1
      - libxkbcommon0
      - libxml2-dev
      - libxml2-utils
      - libxrandr-dev
      - libxrandr2
      - libxrender-dev
      - libxrender1
      - libxshmfence1
      - libxtst6
      - libxxf86vm1
      - libyajl-dev
      - libyajl2
      - lsscsi
      - lua5.1
      - lua5.2
      - lua5.3
      - lzop
      - m4
      - mtools
      - netpbm
      - nilfs-tools
      - ocaml-base-nox
      - ocaml-compiler-libs
      - ocaml-findlib
      - ocaml-interp
      - ocaml-nox
      - opensp
      - perl-openssl-defaults
      - php-all-dev
      - php-common
      - php7.2-cli
      - php7.2-common
      - php7.2-dev
      - php7.2-json
      - php7.2-opcache
      - php7.2-readline
      - pkg-config
      - po-debconf
      - po4a
      - python
      - python-all
      - python-all-dev
      - python-dev
      - python-minimal
      - python2.7
      - python2.7-dev
      - python2.7-minimal
      - python3-all
      - python3-all-dev
      - python3-dev
      - python3-distutils
      - python3-lib2to3
      - python3-mako
      - python3.6-dev
      - qemu-block-extra
      - qemu-system-common
      - qemu-system-x86
      - qemu-utils
      - rake
      - reiserfsprogs
      - ruby
      - ruby-all-dev
      - ruby-did-you-mean
      - ruby-minitest
      - ruby-net-telnet
      - ruby-power-assert
      - ruby-setup
      - ruby-test-unit
      - ruby2.5
      - ruby2.5-dev
      - rubygems-integration
      - scrub
      - seabios
      - sgabios
      - sgml-base
      - shtool
      - sleuthkit
      - syslinux
      - systemtap-sdt-dev
      - ubuntu-mono
      - wireless-regdb
      - x11-common
      - x11proto-composite-dev
      - x11proto-core-dev
      - x11proto-damage-dev
      - x11proto-dev
      - x11proto-fixes-dev
      - x11proto-input-dev
      - x11proto-randr-dev
      - x11proto-xext-dev
      - x11proto-xinerama-dev
      - xml2
      - xorg-sgml-doctools
      - xtrans-dev
      - zfs-fuse
      - zlib1g-dev
      - libjansson-dev
      - libhivex-ocaml-dev
      - bash-completion
      - busybox 
      - dosfstools 
      - iputils-ping 
      - iputils-tracepath 
      - lsof 
      - ntfs-3g 
      - parted 
      - vim-tiny
      - openjdk-8-jdk-headless
      - openjdk-8-jre-headless
