name: octavia-diskimage-retrofit
version: git
summary: tool for retrofitting cloud images for use as Octavia Amphora image.
description: |
  tool for retrofitting cloud images for use as Octavia Amphora image.
confinement: strict
base: core18
grade: devel
environment:
  LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
  LIBGUESTFS_PATH: $SNAP/usr/local/lib/guestfs/appliance
apps:
  virt-dib:
    command: bin/virt-dib
    plugs:
      - network-bind
parts:
  octavia:
    after: [diskimage-builder]
    plugin: dump
    source: https://opendev.org/openstack/octavia.git
    source-type: git
    source-branch: master
    organize:
      elements/*: lib/python3.6/site-packages/diskimage_builder/elements/
  diskimage-builder:
    plugin: python
    source: https://opendev.org/openstack/diskimage-builder.git
    source-type: git
    source-branch: master
    override-build: |
      patch -p1 < ../../../project/patch/patch-diskimage-builder-python3.patch
      snapcraftctl build
  qemu:
    source: https://git.launchpad.net/ubuntu/+source/qemu
    source-type: git
    source-branch: ubuntu/bionic-security
    plugin: autotools
    override-build: |
      dpkg-source --before-build .
      snapcraftctl build
    configflags:
      - --extra-cflags=-g -O2 -fdebug-prefix-map=/home/ubuntu/qemu-2.11+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DCONFIG_QEMU_DATAPATH='"/snap/$SNAPCRAFT_PROJECT_NAME/current/share/qemu:/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/seabios:/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/ipxe/qemu"' -DVENDOR_UBUNTU
      - --extra-ldflags=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed
      - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
      - --libdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/x86_64-linux-gnu
      - --libexecdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/qemu
      - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
      - --disable-blobs
      - --disable-strip
      - --interp-prefix=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/etc/qemu-binfmt/%M
      - --disable-user
      - --enable-system
      - --enable-linux-user
      - --enable-modules
      - --enable-linux-aio
      - --enable-attr
      - --enable-virtfs
      - --enable-cap-ng
      - --enable-curl
      - --enable-fdt
      - --enable-gnutls
      - --disable-gtk
      - --disable-vte
      - --disable-sdl
      - --disable-vnc
      - --disable-vnc-sasl
      - --disable-vnc-jpeg
      - --disable-vnc-png
      - --disable-spice
      - --disable-curses
      - --enable-seccomp
      - --enable-xen
      - --enable-xfsctl
      - --enable-kvm
      - --enable-vhost-net
    build-packages:
      - libaio-dev
      - acpica-tools
      - libattr1-dev
      - libcap-dev
      - libcap-ng-dev
      - libnuma-dev
      - zlib1g-dev
      - uuid-dev
      - device-tree-compiler
      - texinfo
      - libcurl4-gnutls-dev 
      - libfdt-dev 
      - gnutls-dev 
      - libseccomp-dev
      - xfslibs-dev
      - libcapstone-dev
      - pkg-config
      - libpixman-1-dev
      - python-all-dev
      - libglib2.0-dev
    stage-packages:
      - seabios
      - ipxe-qemu
      - libxml2
      - libnuma1
      - libaio1
      - libcurl3-gnutls
      - libxen-dev
      - libcapstone3
      - libfdt1
      - libpixman-1-0
  supermin:
    source: https://github.com/libguestfs/supermin.git
    source-type: git
    source-branch: master
    plugin: autotools
    override-build: |
      ./bootstrap
      snapcraftctl build
    build-packages:
      - e2fslibs-dev
  libguestfs:
    after: [qemu,supermin]
    source: https://git.launchpad.net/ubuntu/+source/libguestfs
    source-type: git
    source-branch: ubuntu/bionic
    plugin: autotools
    build-environment:
      - PYTHON: /usr/bin/python3
      - QEMU: /snap/$SNAPCRAFT_PROJECT_NAME/current/bin/qemu-system-x86_64
    override-build: |
      dpkg-source --before-build .
      patch -p1 < ../../../project/patch/patch-ocaml-lgnu.patch
      patch -p1 < ../../../project/patch/patch-ocaml-examples-gnulib.patch
      mkdir -p /snap/$SNAPCRAFT_PROJECT_NAME
      ln -sf $SNAPCRAFT_STAGE /snap/$SNAPCRAFT_PROJECT_NAME/current
      snapcraftctl build
      rm -f /snap/$SNAPCRAFT_PROJECT_NAME/current
      rmdir /snap/$SNAPCRAFT_PROJECT_NAME
    override-prime: |
      mkdir -p usr/local/lib/guestfs/appliance
      mkdir -p /snap/$SNAPCRAFT_PROJECT_NAME
      ln -sf $SNAPCRAFT_STAGE /snap/$SNAPCRAFT_PROJECT_NAME/current
      env -i LIBGUESTFS_PATH=$SNAPCRAFT_STAGE/lib/guestfs LD_LIBRARY_PATH=$SNAPCRAFT_STAGE/lib:$SNAPCRAFT_STAGE/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET PATH=$SNAPCRAFT_STAGE/usr/sbin:$SNAPCRAFT_STAGE/usr/bin:$SNAPCRAFT_STAGE/sbin:$SNAPCRAFT_STAGE/bin:/usr/sbin:/usr/bin:/sbin:/bin libguestfs-make-fixed-appliance $SNAPCRAFT_PRIME/usr/local/lib/guestfs/appliance
      rm -f /snap/$SNAPCRAFT_PROJECT_NAME/current
      rmdir /snap/$SNAPCRAFT_PROJECT_NAME
      chmod 0644 usr/local/lib/guestfs/appliance/kernel
      snapcraftctl prime
    configflags:
      - --disable-silent-rules
      - --disable-gnulib-tests
      - --with-readline
      - --disable-haskell
      - --disable-java
      - --disable-golang
      - --disable-perl
      - --disable-php
      - --disable-gobject
      - --disable-lua
      - --disable-erlang
      - --disable-ruby
      - --without-libvirt
    stage-packages:
      - libfuse2
      - libmagic1
      - uuid-runtime
    build-packages:
      - bison
      - cpio
      - flex
      - genisoimage
      - gperf
      - libaugeas-dev
      - gettext
      - libfuse-dev
      - libmagic-dev
      - libreadline-dev
      - libyajl-dev
      - ocaml-nox
      - python3-all-dev
